title: Anvi'o Home
email: info@anvio.org
description: "anvi'o is an easy-to-use, open-source, integrated software platform for genomics, metagenomics, metatranscriptomics, pangenomics, metapangenomics, phylogenomics, microbial population genetics, and more."

baseurl: ""

url: "https://anvio.org"

permalink: /blog/:title/

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist
