title: Anvi'o dot org
email: info@anvio.org
description: "Anvi’o is an easy-to-use, open-source, integrated software platform for genomics, metagenomics, metatranscriptomics, pangenomics, metapangenomics, phylogenomics, microbial population genetics, and more."

baseurl: ""

url: "https://anvio.org" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /blog/:title/

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist
